#ifndef ENCLUSTRA_FB_H
#define ENCLUSTRA_FB_H

#define ENCLUSTRA_FB_IOC_MAGIC              'e'
#define ENCLUSTRA_FB_IOC_MAXNR              3

#define ENCLUSTRA_FB_IOC_CMD_SET_BRIGHTNESS _IOW(ENCLUSTRA_FB_IOC_MAGIC, 1, int)
#define ENCLUSTRA_FB_IOC_CMD_DEINIT         _IOW(ENCLUSTRA_FB_IOC_MAGIC, 2, int)
#define ENCLUSTRA_FB_IOC_CMD_REINIT         _IOW(ENCLUSTRA_FB_IOC_MAGIC, 3, int)

#endif /* ENCLUSTRA_FB_H */
